import { useState } from "react";
import { motion } from "framer-motion";
import { ChevronRight } from "lucide-react";
import Navbar from "@/components/landing/Navbar";
import Footer from "@/components/landing/Footer";

const sections = [
  { id: "terms", title: "1. Terms & Conditions" },
  { id: "privacy", title: "2. Privacy Policy" },
  { id: "refund", title: "3. Refund Policy" },
  { id: "user", title: "4. User Policy" },
  { id: "copyrights", title: "5. Copyrights" },
  { id: "cookies", title: "6. Cookies" },
  { id: "billing", title: "7. Account & Billing" },
];

const TermsAndConditions = () => {
  const [activeSection, setActiveSection] = useState("terms");

  const renderContent = () => {
    switch (activeSection) {
      case "terms":
        return (
          <div className="space-y-6">
            <p className="text-muted-foreground leading-relaxed">
              This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
            </p>
            <p className="text-muted-foreground leading-relaxed">
              This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of www.OMShrikanthfinance.in website.
            </p>
            <p className="text-muted-foreground leading-relaxed">
              This Merchant Agreement ("Agreement") is a legal agreement between you ("you", "your") and OMShrikanthfinance Services Private Limited ("OMShrikanthfinance", "we", "our" or "us") governing your use of OMShrikanthfinance's services whereby OMShrikanthfinance shall provide aggregate payment gateway solutions to you for selling Products (as defined below) and/or collecting money for a specified purpose (together, the "OMShrikanthfinance Services").
            </p>
            <p className="text-muted-foreground leading-relaxed">
              When you use OMShrikanthfinance Services provided by us, you will be subject to the rules, guidelines, policies, terms, and conditions applicable to such service, and they shall be deemed to be incorporated into this Agreement and shall be considered as part and parcel of this Agreement. The Privacy Policy form a part of this Agreement. We reserve the right, at our sole discretion, to change, modify, add or remove portions of this Agreement at any time without any prior written notice to you. It is your responsibility to review this Agreement periodically for updates / changes. Your continued use of OMShrikanthfinance Services following the posting of changes will mean that you accept and agree to the revisions.
            </p>
            <p className="text-muted-foreground leading-relaxed">
              This is an important document which you must consider carefully when choosing whether to use OMShrikanthfinance Services at any time. Please read the terms of this Agreement carefully before agreeing to it. This Agreement also highlights certain risks on using the OMShrikanthfinance Services together with guidance on how online payments through OMShrikanthfinance can be facilitated.
            </p>
            <p className="text-muted-foreground leading-relaxed">
              You are solely responsible for understanding and complying with any and all laws, rules and regulations of your specific jurisdiction that may be applicable to you in connection with your business and your use of the OMShrikanthfinance Services.
            </p>
            <p className="text-foreground font-semibold leading-relaxed">
              BY CLICKING THE ACCEPTANCE BUTTON OR ACCESSING, USING OR INSTALLING ANY PART OF THE SERVICE, YOU EXPRESSLY AGREE TO AND CONSENT TO BEING IRREVOCABLY BOUND BY THIS AGREEMENT AND ALL OF THE TERMS SET OUT HEREIN. IF YOU DO NOT AGREE TO ALL OF THE TERMS OF THIS AGREEMENT, THE BUTTON INDICATING NON-ACCEPTANCE MUST BE SELECTED. OMShrikanthfinance WILL PROMPTLY CANCEL THE ASSOCIATION AND YOU MAY NOT ACCESS, USE OR INSTALL ANY PART OF THE SERVICE.
            </p>
            <p className="text-foreground font-semibold leading-relaxed">
              OMShrikanthfinance SHALL HAVE DEEMED TO HAVE ACCEPTED THIS AGREEMENT AND THE CONTRACT SHALL ONLY BE CONSIDERED TO BE DULY EXECUTED, VALID AND BINDING AFTER THE RECEIPT OF THE REQUIRED INFORMATION FROM YOU, DUE VERIFICATION OF THE SAME BY OMShrikanthfinance AND A VERIFICATION OF THE CONTRACT BEING SENT BY OMShrikanthfinance TO YOU AS MORE SPECIFICALLY STATED BELOW.
            </p>
            <p className="text-muted-foreground leading-relaxed">
              THE CONTRACT SHALL BE DEEMED TO HAVE BEEN RECEIVED, ACCEPTED AND FORMED AT OMShrikanthfinance'S REGISTERED OFFICE AT, 24B, SECTOR 16A, NOIDA, UTTAR PRADESH - 201301, INDIA.
            </p>
          </div>
        );
      case "privacy":
        return (
          <div className="space-y-6">
            <p className="text-muted-foreground leading-relaxed">
              This privacy policy (the "PRIVACY POLICY") applies to your use of the website of OMShrikanthfinance hosted at OMShrikanthfinance.in, the Services (as defined under the OMShrikanthfinance "Terms of Use") and OMShrikanthfinance applications on mobile platforms (Android, Windows Phone, iOS etc.) (collectively ("OMShrikanthfinance" or "WEBSITE")), but does not apply to any third-party websites that may be linked to them, or any relationship you may have with the businesses listed on OMShrikanthfinance.
            </p>
            <p className="text-muted-foreground leading-relaxed">
              The terms "WE", "OUR" and "US" refer to OMShrikanthfinance and the terms "YOU", "YOUR" and "USER" refer to you, as a user of OMShrikanthfinance. The term "PERSONAL INFORMATION" means information that you provide to us which personally identifies you to be contacted or identified, such as your name, phone number, email address, and any other data that is tied to such information.
            </p>
            <p className="text-foreground font-semibold mt-6">Complaint Submission Requirements:</p>
            <ul className="list-disc list-inside space-y-2 text-muted-foreground">
              <li>Transaction Date & Time</li>
              <li>Product Name</li>
              <li>Transaction details like unique ID, Amount</li>
              <li>Details of complaint</li>
            </ul>
            <p className="text-muted-foreground leading-relaxed mt-6">
              We have implemented reasonable security practices and procedures that are commensurate with the information assets being protected and with the nature of our business. While we try our best to provide security that is better than the industry standards, because of the inherent vulnerabilities of the internet, we cannot ensure or warrant complete security of all information that is being transmitted to us by you.
            </p>
          </div>
        );
      case "refund":
        return (
          <div className="space-y-6">
            <p className="text-muted-foreground leading-relaxed">
              By accepting to use OMShrikanthfinance Services, you agree to process returns of, and provide refunds and adjustments for, Products sold and/or payment collected through the Merchant Site in accordance with this Agreement, the Acquiring Banks' instructions and Card Association Rules. You understand that no refund shall be processed by OMShrikanthfinance after a period of 180 days from the date of the Transaction.
            </p>
            <div className="bg-card border border-border rounded-lg p-6">
              <p className="text-foreground font-semibold mb-4">You shall:</p>
              <ul className="list-disc list-inside space-y-2 text-muted-foreground">
                <li>Maintain a fair refund, cancellation or adjustment policy</li>
                <li>Disclose its return or cancellation policy to Buyers</li>
                <li>Not give cash refunds to its Buyers in connection with a card sale, unless required by law</li>
                <li>Not accept cash or any other item of value for preparing a card sale refund</li>
              </ul>
            </div>
            <p className="text-muted-foreground leading-relaxed">
              The amount of the refund/adjustment must include any associated taxes required to be refunded and cannot exceed the amount shown as the total on the original sales data except by the exact amount required to reimburse the Customer for postage that the Customer paid to return merchandise.
            </p>
          </div>
        );
      case "user":
        return (
          <div className="space-y-6">
            <p className="text-muted-foreground leading-relaxed">
              The User Online Registration Form, User E-Sign Consent, User Term and Conditions along with our Privacy Policy and Chargeback Policy (collectively this "Agreement") forms the terms and conditions of use of our services ("Services"). This Agreement is a legal document between the User and OMShrikanthfinance Services Private Limited ("OMShrikanthfinance", "we", "our" or "us") governing the Users' relationship with OMShrikanthfinance.
            </p>
            <p className="text-muted-foreground leading-relaxed">
              This is an important document which you must consider carefully when choosing whether to use OMShrikanthfinance Services at any time. Please read the terms of this Agreement carefully before agreeing to it. This Agreement also highlights certain risks on using the OMShrikanthfinance Services together with guidance on how online payments through OMShrikanthfinance can be facilitated.
            </p>
            <p className="text-muted-foreground leading-relaxed">
              You are solely responsible for understanding and complying with any and all laws, rules and regulations of your specific jurisdiction that may be applicable to you in connection with your business and your use of the OMShrikanthfinance Services.
            </p>
          </div>
        );
      case "copyrights":
        return (
          <div className="space-y-6">
            <p className="text-muted-foreground leading-relaxed">
              We record information relating to your use of OMShrikanthfinance, such as the searches you undertake, the pages you view, your browser type, IP address, location, requested URL, referring URL, and timestamp information. We use this type of information to administer OMShrikanthfinance and provide the highest possible level of security and service to you.
            </p>
            <p className="text-muted-foreground leading-relaxed">
              We own all the intellectual property rights associated with the Website and its contents. No right, title or interest in any downloaded material is transferred to you as a result of any such downloading or copying. The Website is protected by copyright as a collective work and/or compilation.
            </p>
            <div className="bg-card border border-border rounded-lg p-6">
              <p className="text-foreground font-semibold mb-4">Our IP Rights:</p>
              <ul className="list-disc list-inside space-y-2 text-muted-foreground">
                <li>Our logos, product and service marks are exclusively owned by us</li>
                <li>Without our prior written permission, you agree to not display and/or use Our IP in any manner</li>
                <li>Nothing contained in this Website should be construed as granting any license or right to Our IP</li>
              </ul>
            </div>
          </div>
        );
      case "cookies":
        return (
          <div className="space-y-6">
            <p className="text-muted-foreground leading-relaxed">
              We send cookies to your computer in order to uniquely identify your browser and improve the quality of our service. The term "cookies" refers to small pieces of information that a website sends to your computer's hard drive while you are viewing the site.
            </p>
            <p className="text-muted-foreground leading-relaxed">
              We may use both session cookies (which expire once you close your browser) and persistent cookies (which stay on your computer until you delete them). Persistent cookies can be removed by following your browser help file directions.
            </p>
            <p className="text-muted-foreground leading-relaxed">
              If you choose to disable cookies, some areas of OMShrikanthfinance may not work properly or at all. OMShrikanthfinance uses third party tools, who may collect anonymous information about your visits to OMShrikanthfinance using cookies, and interaction with OMShrikanthfinance products and services.
            </p>
            <p className="text-muted-foreground leading-relaxed">
              OMShrikanthfinance Users can opt-out of sharing this information with third parties by deactivating cookies, the process of which varies from browser to browser.
            </p>
          </div>
        );
      case "billing":
        return (
          <div className="space-y-6">
            <p className="text-muted-foreground leading-relaxed">
              If you create an account to take advantage of the full range of services offered by OMShrikanthfinance, we ask for and record Personal Information such as your name, email address and mobile number. We may collect and store your Sensitive Personal Data or Information (such as any Financial information including inter alia credit card, debit card details, bank account and know your customer ("KYC") documents as per RBI regulations).
            </p>
            <p className="text-muted-foreground leading-relaxed">
              We use your email address to send you updates, news, and newsletters (if you willingly subscribe to the newsletter during signup, or anytime after signup) and contact you on behalf of other Users. If you do not want to receive communications from us that are not relevant to you, please click on the unsubscribe link provided at the bottom of such e-mails sent to you by us.
            </p>
            <div className="bg-card border border-border rounded-lg p-6">
              <p className="text-foreground font-semibold mb-4">Your Rights:</p>
              <ul className="list-disc list-inside space-y-2 text-muted-foreground">
                <li>You shall have an option to erase any information provided by you including Personal Information</li>
                <li>If a User opts for erasure, OMShrikanthfinance shall delete all stored information from its servers</li>
                <li>Your Personal Information will not be made public or sold to any third party</li>
              </ul>
            </div>
          </div>
        );
      default:
        return null;
    }
  };

  return (
    <div className="min-h-screen bg-background flex flex-col">
      <Navbar />

      <div className="flex-1">
        {/* Breadcrumb */}
        <div className="border-b border-border bg-card/50">
          <div className="container mx-auto container-padding py-6">
            <div className="flex items-center gap-2 text-sm">
              <a href="/" className="text-primary hover:text-primary/80 transition-colors">
                Home
              </a>
              <ChevronRight className="h-4 w-4 text-muted-foreground" />
              <span className="text-muted-foreground">Terms and Conditions</span>
            </div>
          </div>
        </div>

        {/* Main Content */}
        <div className="container mx-auto container-padding py-16">
          <div className="grid gap-8 lg:grid-cols-4">
            {/* Sidebar */}
            <motion.div
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.5 }}
              className="lg:col-span-1"
            >
              <div className="sticky top-24 space-y-2">
                <p className="text-sm font-semibold text-foreground mb-4">Contents</p>
                {sections.map((section) => (
                  <button
                    key={section.id}
                    onClick={() => setActiveSection(section.id)}
                    className={`block w-full text-left px-4 py-3 rounded-lg transition-all duration-200 ${
                      activeSection === section.id
                        ? "bg-primary text-white font-medium"
                        : "text-muted-foreground hover:bg-card hover:text-foreground"
                    }`}
                  >
                    {section.title}
                  </button>
                ))}
                <div className="pt-6 border-t border-border mt-6">
                  <p className="text-xs font-semibold text-foreground mb-3 uppercase">Related Pages</p>
                  <a
                    href="/privacy-policy"
                    className="block w-full text-left px-4 py-3 rounded-lg text-muted-foreground hover:bg-card hover:text-foreground transition-all duration-200 text-sm"
                  >
                    Privacy Policy
                  </a>
                </div>
              </div>
            </motion.div>

            {/* Content */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5 }}
              className="lg:col-span-3"
            >
              <div className="space-y-8">
                <div>
                  <h1 className="text-3xl md:text-4xl font-bold text-foreground mb-4">
                    {sections.find((s) => s.id === activeSection)?.title}
                  </h1>
                  <div className="h-1 w-20 bg-gradient-to-r from-primary to-accent rounded-full" />
                </div>

                <div className="prose prose-invert max-w-none">
                  {renderContent()}
                </div>
              </div>
            </motion.div>
          </div>
        </div>
      </div>

      <Footer />
    </div>
  );
};

export default TermsAndConditions;

